### ISSUE TITLE
Implement read EK cert nvram

### ISSUE THREAD

**Issue by lukehinds** [keylime/rust-keylime#117]
The following function is required:

https://github.com/keylime/keylime/blob/72c04b05bfb8990d1ac68186657ac27f30902503/keylime/tpm/tpm2.py#L1212

The function first relies on the implementation of issues #114 , #115 and #116

**Comment by puiterwijk** [comment]
This is already in tss-esapi: https://docs.rs/tss-esapi/4.0.10-alpha.2/tss_esapi/abstraction/ek/fn.retrieve_ek_pubcert.html

**Comment by lkatalin** [comment]
@lukehinds @puiterwijk Should we close this issue in light of the tss-esapi implementation?
