### ISSUE TITLE
Implement write of tpm metadata

### ISSUE THREAD

**Issue by lukehinds** [keylime/rust-keylime#118]
Implement the following function

https://github.com/keylime/keylime/blob/72c04b05bfb8990d1ac68186657ac27f30902503/keylime/tpm/tpm_abstract.py#L248

This first requires object creation implemented in issues #115 , #115 , #116 and #117

**Comment by lkatalin** [comment]
@lukehinds @puiterwijk Is there any more context on this? Maybe we can discuss at one of our meetings this week.

**Comment by lkatalin** [comment]
Closing as we are no longer doing this in Keylime.
