### ISSUE TITLE
Bug: CI Build Failure

### ISSUE THREAD

**Issue by lukehinds** [keylime/rust-keylime#123]
even though we install `libtss-dev` , the build still fails;

https://github.com/keylime/rust-keylime/pull/122/checks?check_run_id=1226039369#step:5:133

**Comment by lukehinds** [comment]
https://bugs.launchpad.net/ubuntu/+source/tpm2-tss/+bug/1901486

**Comment by lkatalin** [comment]
@lukehinds Should we close this? Looks like it was fixed in #140 (I think)
