### ISSUE TITLE
Remove all calls that might panic

### ISSUE THREAD

**Issue by frozencemetery** [keylime/rust-keylime#19]
It's not going to be okay for the process to crash, which is what `panic!()` does.  Removal includes all calls to `unwrap()`, `assert!()`, and the like (except in test suite code).

Ideally this work would also include some CI to prevent anything that panics from getting added in new code as well.

**Comment by frozencemetery** [comment]
My suggestion is to add something like [no_panic] for CI purposes.  @leonjia0112 please investigate.

**Comment by leonjia0112** [comment]
Got it.

**Comment by leonjia0112** [comment]
This crate is able to detect panic in rust.
https://crates.io/crates/no-panic

Will apply it in later PR.

**Comment by frozencemetery** [comment]
Resolved enough for now in c0872975525f398d22a1bdee831de81ab38fa7bb
