### ISSUE TITLE
Crypto interface

### ISSUE THREAD

**Issue by frozencemetery** [keylime/rust-keylime#20]
All cryptographic operations should be done either on the TPM or through a rust openssl shim.  Interface should hide all "tricky bits" from the rest of keylime.

**Comment by lukehinds** [comment]
I think we can close this now, according to the above merged PR?

**Comment by frozencemetery** [comment]
@mbestavros can you speak to this?

**Comment by mbestavros** [comment]
There are still a few stubs we need that aren't done yet; some are WIP on my end. I'm currently working on building our custom `CryptoError` type for everything in `crypto.rs`  (#42) before doing further work on bindings.
