### ISSUE TITLE
need to lazy load or reconsider how we load revocation

### ISSUE THREAD

**Issue by lukehinds** [keylime/rust-keylime#202]
In the python agent they lazy load `RevocationNotifier-cert.crt`. The reason for this is that the agent cannot access `RevocationNotifier-cert.crt` (from secure/unzipped) until after its received the unzipped payload from the `keylime_tenant` first (which contains the `RevocationNotifier-cert.crt` file and others). The reason for this is you can't provision the agent to receive the payload unless its running first.

## debug example

```
RUST_LOG=keylime_agent=trace cargo run
   Compiling keylime_agent v0.1.0 (/root/rust-keylime)
    Finished dev [unoptimized + debuginfo] target(s) in 6.83s
     Running `target/debug/keylime_agent`
 INFO  keylime_agent > Starting server...
 INFO  keylime_agent > Misformatted UUID: neptune
 INFO  keylime_agent::registrar_agent > Sending data to http://127.0.0.1:8890/agents/ffd57add-d217-4a81-ade3-e140b648df3a
 INFO  keylime_agent                  > SUCCESS: agent registered
 INFO  keylime_agent                  > SUCCESS: agent activated
 INFO  keylime_agent                  > Listening on http://127.0.0.1:9002
 INFO  keylime_agent::secure_mount    > Using existing secure storage tmpsfs mount /tmp/secure
 INFO  keylime_agent::revocation      > Connecting to revocation endpoint at tcp://127.0.0.1:8992...
 ERROR keylime_agent::revocation      > Path /tmp/secure/unzipped/RevocationNotifier-cert.crt for the 0mq socket doesn't exist
Error: Configuration("Path /tmp/secure/unzipped/RevocationNotifier-cert.crt for the 0mq socket socket doesn't exist")
```

**Comment by lukehinds** [comment]
Looking at the code we could take the following code and put this into a function

https://github.com/keylime/rust-keylime/blob/f51f6500f62aa4e9ff9381b842e4307630d2c506/src/revocation.rs#L144-L166

And then call the function from line 206-207

https://github.com/keylime/rust-keylime/blob/f51f6500f62aa4e9ff9381b842e4307630d2c506/src/revocation.rs#L205-L209

Would that work do you think @lkatalin , this way we only load when we successfully parse out the body message?

**Comment by lkatalin** [comment]
@lukehinds Thanks for looking at it, I think this change would make sense. Additionally, if a revocation message is received very soon after launching the agent (before attestation / payload decryption is complete), it seems this could still fail because the body message would be parsed from the revocation message and it would go on to check for the revocation cert, which still wouldn't be there yet. Do you think it makes sense to launch the revocation service only after payload decryption is complete? Because this is what I'm setting up currently in the last PR (which deals with handling U and V keys and decrypting the payload).

**Comment by lkatalin** [comment]
We've had some discussion (@lkatalin and @mpeters ) around what the tenant's payload contains, and that it should contain anything the tenant wants (makes sense as it aligns with the principle that this is totally configurable). In light of this, can the agent necessarily expect this certificate to be present after receiving the payload? @lukehinds any thoughts?

**Comment by lkatalin** [comment]
> We've had some discussion (@lkatalin and @mpeters ) around what the tenant's payload contains, and that it should contain anything the tenant wants (makes sense as it aligns with the principle that this is totally configurable). In light of this, can the agent necessarily expect this certificate to be present after receiving the payload? @lukehinds any thoughts?

Just an FYI for posterity: Apparently the tenant hardcodes the revocation certificate file name, thus if one uses the tenant with the  `--cert` flag, it will just set up the revocation certificate the agent looks for (also hardcoded) automatically. As long as the user knows to use `--cert` with the tenant, this workflow does make sense.
