### ISSUE TITLE
Add option to decrypt older payload from file

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#207]
Currently the Rust code assumes there is one payload that was just delivered from the tenant. The Python code has another option to decrypt an older payload (see [here](https://github.com/keylime/keylime/blob/master/keylime/keylime_agent.py#L247)). It also writes out the current encrypted payload so it can be decrypted next time:

```
 elif os.path.exists(enc_path):
            # if no payload provided, try to decrypt one from a previous run stored in encrypted_payload
            with open(enc_path, 'rb') as f:
                enc_payload = f.read()
            try:
                dec_payload = crypto.decrypt(enc_payload, self.server.K)
                logger.info("Decrypted previous payload in %s to %s", enc_path, dec_path)
            except Exception as e:
                logger.warning("Unable to decrypt previous payload %s with derived key: %s", enc_path, e)
                os.remove(enc_path)
                enc_payload = None

        # also write out encrypted payload to be decrytped next time
        if enc_payload is not None:
            with open(enc_path, 'wb') as f:
                f.write(self.server.payload.encode('utf-8'))

```

We should add this functionality.

**Comment by mpeters** [comment]
I'm not sure if this is a "feature" that people use as much as a fall back mechanism to recover from fail cases. Would be good to get some historical perspective on it.

**Comment by lkatalin** [comment]
Thanks @mpeters . Also related: #206

**Comment by lkatalin** [comment]
Another reason I'm not sure this makes sense is that apparently in the Python code, the `unzipped` directory is wiped on each run, meaning this previous payload wouldn't stick around anyway... https://github.com/keylime/keylime/blob/master/keylime/keylime_agent.py#L221

**Comment by lkatalin** [comment]
The consensus for now is we may eventually want to retain attestation artifacts for auditing, but this is not yet fully developed in Python and does not need to go in the first version of the Rust agent.

**Comment by lkatalin** [comment]
Closing in favor of #235
