### ISSUE TITLE
Ensure logging output matches Python

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#213]
We should have a logging message everywhere that the Python agent does. It is okay if we also have additional verbose, helpful output, esp in case of errors.

**Comment by lkatalin** [comment]
#201 is a subset of this.

**Comment by lkatalin** [comment]
Note: if you take on this issue, please DO NOT remove the existing logging statements. Only add more. : )

**Comment by ansasaki** [comment]
@lkatalin Hello, is the goal here to have exactly matching output or to have corresponding messages in both implementations?

If it is the latter, I would like to take this.
