### ISSUE TITLE
Installer that doesn't download anything

### ISSUE THREAD

**Issue by frozencemetery** [keylime/rust-keylime#23]
As part of packaging, we're going to need an install script that sets up everything without downloading stuff from the internet.  Eventually we may want to do away with it entirely, but that's probably out of scope.

**Comment by ashcrow** [comment]
There are some things we can do to make this build offline. For some other projects I see the use of an extra source which is the crates as a "vendor" and then the cargo registry is pointed to the local create location. In [this packaging documentation](https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/) there is a pointer to `%cargo_prep` which does [handle some of this as well](https://pagure.io/fedora-rust/rust2rpm/blob/master/f/data/macros.cargo#_16).
