### ISSUE TITLE
Multiple PCR reads necessary when many PCRs requested

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#234]
According to @puiterwijk : if more than 8 PCR datas are requested (including e.g. 7 sha256 and 2 sha1 values), a single pcr_read won't suffice, and we'll need to get multiple reads, and combine the results

**Comment by lkatalin** [comment]
This is apparently a critical bug, but should be an easy fix.

**Comment by lkatalin** [comment]
This bug has to do with the size of the [`TPML_DIGEST`](https://github.com/parallaxsecond/rust-tss-esapi/blob/main/tss-esapi-sys/src/bindings/x86_64-unknown-linux-gnu.rs#L1933). This is the function [`pcr_read`](https://github.com/parallaxsecond/rust-tss-esapi/blob/8ce5af0d01496619fa993d0ed3a43bd941754e9b/tss-esapi/src/context/tpm_commands/integrity_collection_pcr.rs#L155) that is using the `TPML_DIGEST` struct to hold data.

@puiterwijk After reviewing our earlier convo, I think you are saying this patch would *not* be on the ESAPI side? So could it be something as simple as doing several `pcr_read`s and extending the results into one long `PcrData` vec before returning from [`make_pcr_blob()`](https://github.com/keylime/rust-keylime/blob/e5cec6ff3bdf9d50ebfc76e008ec9b5036a22d22/src/tpm.rs#L581)? Because if so, then I can implement it.

**Comment by aplanas** [comment]
Can this be the same?

```
ERROR actix_http::response > Internal Server Error: Other("could not read all pcrs; requested: PcrSelectionList { items: [PcrSelection { hashing_algorithm: Sha256, size_of_select: ThreeBytes, selected_pcrs: BitFlags<PcrSlot>(0b11111101111111111, Slot0 | Slot1 | Slot2 | Slot3 | Slot4 | Slot5 | Slot6 | Slot7 | Slot8 | Slot9 | Slot11 | Slot12 | Slot13 | Slot14 | Slot15 | Slot16) }] }, read: PcrSelectionList { items: [PcrSelection { hashing_algorithm: Sha256, size_of_select: ThreeBytes, selected_pcrs: BitFlags<PcrSlot>(0b11111111, Slot0 | Slot1 | Slot2 | Slot3 | Slot4 | Slot5 | Slot6 | Slot7) }] }")
```

**Comment by THS-on** [comment]
@aplanas looks like it because the agent tries to request more than 8 PCRs at once.
