### ISSUE TITLE
Promote Daiki Ueno to maintainer

### ISSUE THREAD

**Issue by lukehinds** [keylime/rust-keylime#250]
Daiki Ueno has made some great contributions as of late and has a lot of experience maintaining low level crypto libraries. I therefore think it makes sense to promote Daiki to a maintainer in rust keylime.

Maintainers please respond with +1's or feedback.

https://github.com/ueno

**Comment by lukehinds** [comment]
Cc @lkatalin @ashcrow @mpeters @puiterwijk

**Comment by lkatalin** [comment]
+1 I agree!
