### ISSUE TITLE
Support incremental attestation

### ISSUE THREAD

**Issue by ueno** [keylime/rust-keylime#260]
As part of https://github.com/keylime/keylime/pull/676, the `ima_ml_entry` parameter has been added to the REST API, which allows the agent to omit sending entries already seen by the verifier.

**Comment by ansasaki** [comment]
@ueno @lkatalin Could you confirm this can be closed via #339?

**Comment by lkatalin** [comment]
I would think so unless @ueno knows of anything missing.
