### ISSUE TITLE
Implement config parser

### ISSUE THREAD

**Issue by lukehinds** [keylime/rust-keylime#27]
A few values are appearing in the code that we could make available for users in a config file, using the [config crate](https://docs.rs/config/0.9.1/config/). For example the IP and Port values [here](https://github.com/redhat-university-partnerships/keylime/blob/master/src/main.rs#L47)

**Comment by lukehinds** [comment]
can assign to me if happy with the idea, also we could create some labels like (won't fix, invalid, question etc).

**Comment by frozencemetery** [comment]
@leonjia0112 proposed something similar in https://github.com/redhat-university-partnerships/keylime/pull/18

I think you're both right that it makes sense to have a config file.  My concerns with that PR were twofold: first, compatibility with MIT, and second, not exposing options unnecessarily.  (The more handles we have, the more possible misconfigurations there are.)

[MIT](https://github.com/mit-ll/python-keylime#configuring-keylime) puts the config file at /etc/keylime.conf, with an environment variable indicating path to alternate configuration.  They also seem to be using an INI-style file there as expected, with [separate section for the cloud node](https://github.com/mit-ll/python-keylime/blob/master/keylime.conf#L36) (as well as some general options we probably should look at too).

That said, I think this should be used as a starting point, not a final decider.  We probably won't want all the features they've implemented (definitely not in a first pass, at any rate).

**Comment by leonjia0112** [comment]
May I reopen the PR for another review? I think we can use that config parser for storing the registrar IP address and port number at this point, which is needed in cloud_node functions.

**Comment by lukehinds** [comment]
good point @frozencemetery , so we should use the existing namespace [cloud_node] and `/etc/keylime.conf` naming [0]

This way if folks run an "all in one" single machine deployment for testing / development they can have a single config for all values, and if they run a server / client arch, then the rust cloud node will only parse out the [cloud_node] section. 

[0] https://github.com/mit-ll/python-keylime/blob/master/keylime.conf#L36
