### ISSUE TITLE
Don't hardcode endianness

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#283]
Use the host endianness instead of `to_le_bytes()` or `to_be_bytes()`. I think there is an easy way to do this from `byteorder` but I'd have to look again.

**Comment by ansasaki** [comment]
Check if this is actually valid: the encoding is kept the same independently of the arch to avoid encoding errors due to endianess. A good approach to check is to test the changes proposed in #637 mixing big endian and little endian arches
