### ISSUE TITLE
Support getting pubkey via API

### ISSUE THREAD

**Issue by mbestavros** [keylime/rust-keylime#284]
Keylime's Python agent supports getting pubkeys via the `/keys/pubkey` endpoint. This does not yet appear to be implemented in `rust-keylime` when testing Keylime against the Rust agent, however, as seen [here](https://github.com/keylime/keylime/pull/812).

Implementation of the API is necessary for `rust-keylime` to pass the Keylime test suite.

**Comment by lkatalin** [comment]
Thanks for opening this @mbestavros ; I had not been able to find a clear answer on whether we're going to use this functionality. Looks like we should go ahead and include it.
