### ISSUE TITLE
Support getting quote integrity via API

### ISSUE THREAD

**Issue by mbestavros** [keylime/rust-keylime#285]
Keylime's Python agent supports getting quote integrity via the `/quotes/integrity` endpoint. This does not yet appear to be implemented in `rust-keylime` when testing Keylime against the Rust agent, however, as seen [here](https://github.com/keylime/keylime/pull/812).

The endpoint takes parameters:

- `?nonce`
- `?mask`
- `?vmask`
- `?partial`

Implementation of the API is necessary for `rust-keylime` to pass the Keylime test suite.

**Comment by lkatalin** [comment]
Is this different from returning an integrity quote? We have a handler that returns these quotes already and takes parameters like nonce and mask. Is the specific failing test [`test_040_agent_quotes_integrity_get`](https://github.com/keylime/keylime/blob/master/test/test_restful.py#L816)?

**Comment by mbestavros** [comment]
@lkatalin Yes. Is this something where we might need to change the endpoint the test hits?

**Comment by lkatalin** [comment]
I'm not really sure... we have a `/quotes/integrity` handler [here](https://github.com/keylime/rust-keylime/blob/master/src/main.rs#L431) already. Do you know what the exact error is that it gives you when you try to test it?

**Comment by mbestavros** [comment]
@lkatalin It's just a 404 error when we make the request. My assumption was that meant it wasn't yet implemented. Maybe it's something more?

**Comment by ueno** [comment]
I've just run the test locally and it seems 404 is returned because the agent cannot access `/sys/kernel/security/ima/ascii_runtime_measurements` (actix-web maps `std::io:ErrorKind::NotFound` to 404).

**Comment by lkatalin** [comment]
This appears to be fixed as of https://github.com/keylime/keylime/pull/1109
