### ISSUE TITLE
keylime_agent --help errors out when system setup is incomplete

### ISSUE THREAD

**Issue by kkaarreell** [keylime/rust-keylime#287]
# keylime_agent --help

** (process:31217): WARNING **: 13:34:53.978: Failed to create connection with service: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer.
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: tabrmd 
ERROR:tcti:src/tss2-tcti/tctildr.c:428:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
 ERROR tss_esapi::tcti_ldr > Error when creating a TCTI context: response code not recognized
Error: Tpm { err: Tss2Error(FormatZero(FormatZeroResponseCode { .0: 655368, error_number: 8, format_selector: false, version: false, tcg_vendor_indicator: false, severity: false })), kind: None, message: "response code not recognized" }

--help should work even when system is not configured as required.

**Comment by lkatalin** [comment]
This is a good point! Thanks for opening this issue. We will put it on our to-do list.

**Comment by lkatalin** [comment]
This would be a good first issue, perhaps with [`clap`](https://docs.rs/clap/3.0.5/clap/).
