### ISSUE TITLE
Implement error.rs

### ISSUE THREAD

**Issue by lukehinds** [keylime/rust-keylime#288]
There are going to be a lot of error types that need managing, so lets create an error handler.

**Comment by lkatalin** [comment]
@lukehinds Do you mean something beyond our [`src/error.rs`](https://github.com/keylime/rust-keylime/blob/master/src/error.rs) file? It has a number of error types as well as conversions between them where useful.

**Comment by lukehinds** [comment]
> @lukehinds Do you mean something beyond our [`src/error.rs`](https://github.com/keylime/rust-keylime/blob/master/src/error.rs) file? It has a number of error types as well as conversions between them where useful.

Yes, exactly that!

**Comment by lukehinds** [comment]
raised this in the wrong repo!
