### ISSUE TITLE
Add a way to compile out ZeroMQ support

### ISSUE THREAD

**Issue by ueno** [keylime/rust-keylime#298]
As noted in #199 libzmq brings in quite a few dependencies, while this feature is not always desired. It might be worth considering a Cargo feature to compile out the support. This could be done something like in Cargo.toml:
```toml
[features]
default = ["revocation"]
revocation = ["zmq"]
```
in the source, using the [cfg_if](https://docs.rs/cfg-if/1.0.0/cfg_if/) crate:
```rust
cfg_if::cfg_if! {
    if #[cfg(feature = "revocation")] {
        ...
    }
}
```
and then you could compile the crate with `--no-default-features`.

Additional note:
- Proper support for revocation events (including actions) through alternative means would need to wait for keylime/enhancements#54 and keylime/enhancements#56 being implemented, which is out of scope of this issue
- Making it a dynamically loadable [plugin](https://michael-f-bryan.github.io/rust-ffi-guide/dynamic_loading.html) might be an option, though I guess it would require significant work

**Comment by lkatalin** [comment]
I like the idea of having this as a feature.

Re: the dynamic plugin, I thought this was already the approach we're taking since each revocation action takes some type of JSON input? [Example](https://github.com/keylime/rust-keylime/blob/master/src/revocation.rs#L20)

**Comment by lkatalin** [comment]
@ueno has mentioned that the way forward on this is by implementing the proposal in https://github.com/keylime/enhancements/blob/master/53_agent_local_revocation.md. @ansasaki is this something that you are planning to implement?

Do we still also want to have revocation as an optional feature as well? It could make sense.

**Comment by ueno** [comment]
> Re: the dynamic plugin, I thought this was already the approach we're taking since each revocation action takes some type of JSON input? [Example](https://github.com/keylime/rust-keylime/blob/master/src/revocation.rs#L20)

To be clear, I meant to dynamically load libzmq itself, not the revocation actions.

> Do we still also want to have revocation as an optional feature as well? It could make sense.

I believe this is still necessary, because libzmq and its dependencies are not always available (e.g., on CentOS/RHEL) nor usable under FIPS restrictions.

**Comment by ansasaki** [comment]
> @ueno has mentioned that the way forward on this is by implementing the proposal in https://github.com/keylime/enhancements/blob/master/53_agent_local_revocation.md. @ansasaki is this something that you are planning to implement?

Yes, I'm planning to implement that enhancement

**Comment by lkatalin** [comment]
@ansasaki Would it be possible / does it makes sense from your perspective to prioritize this over other incoming PRs?

**Comment by ansasaki** [comment]
> @ansasaki Would it be possible / does it makes sense from your perspective to prioritize this over other incoming PRs?

Sure, I have the changes ready, just running some tests before creating the PR.
