### ISSUE TITLE
Remove workaround for missing Content-Type: application/json

### ISSUE THREAD

**Issue by ueno** [keylime/rust-keylime#306]
Until keylime/keylime#845 the tenant and the verifier didn't set the Content-Type header properly, which required the actix handlers to manually deserialize JSON payload (for [ukey](https://github.com/keylime/rust-keylime/blob/15f467d1083625696a3a26a5a3a5837fea6c8323/src/keys_handler.rs#L84) and [vkey](https://github.com/keylime/rust-keylime/blob/15f467d1083625696a3a26a5a3a5837fea6c8323/src/keys_handler.rs#L141)). We should remove the workaround once the new python keylime has been released.

**Comment by ansasaki** [comment]
@ueno Can we remove the workaround now?
