### ISSUE TITLE
Bump API version

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#311]
Keylime is dropping support for API v1.0 https://github.com/keylime/keylime/pull/862

We should make sure the Rust agent is compliant with any 2.0 requirements and bump the [API version](https://github.com/keylime/rust-keylime/blob/318dfdec5ce30c520e5f17bc2b03c422a198a1a4/src/common.rs#L22).

**Comment by THS-on** [comment]
I have a mostly finished patch for the mTLS support which I'll post once I re-based it on master.

**Comment by lkatalin** [comment]
> I have a mostly finished patch for the mTLS support which I'll post once I re-based it on master.

Awesome!
