### ISSUE TITLE
Use /proc/self/mountinfo instead of mount for checking secure mount point

### ISSUE THREAD

**Issue by THS-on** [keylime/rust-keylime#317]
The output of `mount` does not escape spaces which might lead to unexpected behavior that fools the agent that the mount is actually there:  https://github.com/keylime/keylime/security/advisories/GHSA-wj36-qcfg-5j52

We fixed this in the Python agent by parsing `/proc/self/mountinfo` instead. I think the rust agent is also affected by this.

Logic from the Python agent can be found here: https://github.com/keylime/keylime/blob/15663f08b5d94ae716cd971b8a1215121cc1acb1/keylime/secure_mount.py#L19-L60

**Comment by ansasaki** [comment]
Fixed via #364
