### ISSUE TITLE
Add "currently" to swtpm warning

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#323]
https://github.com/keylime/keylime/pull/881

**Comment by sarroutbi** [comment]
@lkatalin: Should this issue be closed? Does [keylime/keylime#881](https://github.com/keylime/keylime/pull/881) handle this?

**Comment by sarroutbi** [comment]
OK. Thanks for clarifying. I will try and open a PR for that. Thanks !!!
