### ISSUE TITLE
allow absolute paths for NK and mTLS certificate

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#324]
https://github.com/keylime/keylime/pull/879

**Comment by THS-on** [comment]
Ideally I want to put all the keys (TPM and transport) and the certificate into one single file which is different to what the Python agent is doing. The reason for this is to allow pre provision all this data more easily.

https://github.com/keylime/rust-keylime/pull/316 does not persist any data at all and when this changed in the future I think it is fine to differ from the Python agent.

**Comment by THS-on** [comment]
We now persist all the NK and mTLS data in the `agent_data.json` file.
