### ISSUE TITLE
add localhost, server and contact ip to agent certificate

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#327]
https://github.com/keylime/keylime/pull/886

**Comment by ansasaki** [comment]
> Hello. I have started working on this (#744), but I doubt how to proceed with configuration of the contact IP ... should we set a specific optional parameter in agent configuration?

The `contact_ip` option is already present in the agent configuration file.

I think this is about:

- modifying `generate_x509` in `keylime-agent/src/crypto.rs` to receive the contact ip (and maybe other extra DNS names) as optional parameters
- in main, obtain the value from the configuration for `contact_ip` and pass to the modified `generate_x509` to be included in the certificate
