### ISSUE TITLE
Implement use of KEYLIME_DIR env var

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#333]
Use the env variable `KEYLIME_DIR` to set the current working directory. The default is `/var/lib/keylime`. But, during e2e testing, it should be set to something like `/root/keylime`. I believe the e2e tests would have to set this var, it isn't set in the agent; but the agent needs to recognize it and choose locations like [where to look for the CA cert](https://github.com/keylime/rust-keylime/blob/master/src/common.rs#L34) based on it.

**Comment by ansasaki** [comment]
Can I assign this to myself?

**Comment by lkatalin** [comment]
> Can I assign this to myself?

@ansasaki Absolutely! Thanks for volunteering.
