### ISSUE TITLE
keylime agent stops with error if payload_script is not found

### ISSUE THREAD

**Issue by ansasaki** [keylime/rust-keylime#336]
The keylime agent will stop execution with error if the `payload_script` is set in configuration but is not provided in the payload.

It should follow python agent behavior which ignores the `payload_script` if it is not found:
https://github.com/keylime/keylime/blob/70f538aedf99c5ab4dc23113e3e2ecb94a2402a8/keylime/keylime_agent.py#L333-L351

**Comment by lkatalin** [comment]
Thanks for opening this issue, I agree.
