### ISSUE TITLE
Repo naming

### ISSUE THREAD

**Issue by lukehinds** [keylime/rust-keylime#34]
Really low priority issue, but opening for discussion.

At some point we should maybe consider renaming the repository to something like `keylime_cloudnode` or at least something less global than `keylime`.

I can totally see the justification for it currently being `keylime` as its a collection point for the work efforts around keylime (we have the RPM spec file here), but over time I expect various automation frameworks will be cloning this and the MIT repository and the resulting folders are currently:

    python-keylime/
    keylime/

As I say, not a big issue at all, so can be marked as wishlist for now as its not impeding work.

**Comment by frozencemetery** [comment]
It's definitely a discussion we should have in the future.  I think the name itself will depend a lot on what our scope ends up being - we've discussed going further than the cloud node in the future, but that's currently too far off to really plan around.

There's also a question of org ownership.  When we have something serious I think it would make sense to move us off the redhat-university-partnerships org and onto our own - at which point we could also split out cloud node, automation, rpm goo, etc.

**Comment by lukehinds** [comment]
> There's also a question of org ownership. When we have something serious I think it would make sense to move us off the redhat-university-partnerships org and onto our own - at which point we could also split out cloud node, automation, rpm goo, etc.

I was actually thinking about that too, agree its not something we need to yet though, but would be a useful set up, the project could have its own github pages (seems that's not possible per repo, only per user or org).

**Comment by frozencemetery** [comment]
Closing since we've moved orgs and renamed.
