### ISSUE TITLE
Graceful shutdown of the agent

### ISSUE THREAD

**Issue by ueno** [keylime/rust-keylime#363]
Currently the agent does not perform any cleanup when the process is terminated with a signal. We could do:
- send `TPM2_SHUTDOWN` (though we rely on the resource manager)
- remove any leftover files in the secure mount directory

This came out of the discussion at #334.

**Comment by Koncpa** [comment]
This issue blocking possible new [feature](https://github.com/RedHat-SP-Security/keylime-tests/pull/217) in keylime tests upstream.

**Comment by Koncpa** [comment]
I wonder if changing the kill signal in the [service file](https://github.com/keylime/rust-keylime/blob/003f6a94632d05adfe86e7f5e14d7ae8afc06ec9/dist/systemd/system/keylime_agent.service#L15) for the agent would be enough to solve this problem. What do you think @ansasaki ?

**Comment by THS-on** [comment]
> I wonder if changing the kill signal in the [service file](https://github.com/keylime/rust-keylime/blob/003f6a94632d05adfe86e7f5e14d7ae8afc06ec9/dist/systemd/system/keylime_agent.service#L15) for the agent would be enough to solve this problem. What do you think @ansasaki ?

Not @ansasaki, but there is currently no real signal handler implemented in the rust agent. We need to write our own that shutdowns the aticx server, revocation listener and TPM gracefully.

**Comment by Koncpa** [comment]
Thanks for explanation @THS-on!
