### ISSUE TITLE
Agent fails to start if `shim.py` is not found

### ISSUE THREAD

**Issue by maugustosilva** [keylime/rust-keylime#368]
# Environment

OS: FC35
`Verifier`/`Registrar`: v6.4.0
`Agent`: b869a6a(master).

# Symptom

```
 WARN  keylime_agent > INSECURE: Keylime is using a software TPM emulator rather than a real hardware TPM.
 WARN  keylime_agent > INSECURE: The security of Keylime is NOT linked to a hardware root of trust.
 WARN  keylime_agent > INSECURE: Only use Keylime in this mode for testing or debugging purposes.
 INFO  keylime_agent > Starting server with API version v2.0...
 ERROR keylime_agent > Could not find python shim at /usr/libexec/keylime/shim.py
Error: Configuration("Could not find python shim at /usr/libexec/keylime/shim.py")
```

# Workaround

```
mkdir -p /usr/libexec/keylime
touch /usr/libexec/keylime/shim.py
```

Perhaps a more operations-friendly option, where the agent can start (albeit with reduced capabilities) could be considered.

**Comment by lkatalin** [comment]
> I propose we make the support for python revocation actions optional, enabled by default for now, and we can remove the support completely later. The idea is to use a mechanism similar to the one used to remove ZeroMQ dependency.

I think this would be a good way to do it.

**Comment by maugustosilva** [comment]
Allow me to suggest an additional refinement to your proposal @ansasaki: In case `listen_notifications = False` under `[cloud_agent]`, then do **not** return error on initialization if `shimp.py` is not in place

**Comment by ansasaki** [comment]
> Ah, I see... notifications via REST API are possible, ok. Being that the case, you're correct: provide a flag on the `[cloud_agent]` section of keylime configuration file to **disable** "python revocation actions", in which case the agent does not look for `shim.py`.

The PR I proposed (#377) adds the  `legacy-python-actions` feature, which can be disabled in compile time to drop the related code, therefore is not a configuration option that can be enabled/disabled later. The plan is to deprecate this feature and ultimately remove it completely when the rust agent is the official agent.

@maugustosilva Do you think it would be necessary to make it a configuration option which can be enabled/disabled?

**Comment by maugustosilva** [comment]
Not at all... since it will be deprecated soon enough, I agree, let's leave it as compile option only.
