### ISSUE TITLE
agent fails due to no var/lib/keylime

### ISSUE THREAD

**Issue by lukehinds** [keylime/rust-keylime#388]
On a fresh install of Fedora 35

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/7058938/171568177-646663f5-ebe9-4bc3-b698-2cd9d464c929.png">

Should I create this manually:

It has various errors missing event log , Invalid parameter format, missing python shim

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/7058938/171568397-bc7862a8-3ecb-40ce-b8a4-3da7314f27ef.png">

If manual setup steps are required, we should document them.

**Comment by lukehinds** [comment]
Ahh, I see we have a Makefile now.

**Comment by ansasaki** [comment]
The current package in Fedora does not install the secure mount systemd unit which mounts the `/var/lib/keylime/secure` path. On next package update the service will be installed properly (the update will come after we have the beta release).

For now, as a workaround, it is possible to use the Makefile to install the services or install them manually (the unit file are provided in `dist/systemd/system/`)
