### ISSUE TITLE
Unhelpful error when EK cert is not available

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#389]
From @lukehinds running the agent on GCP, the error "no such file or directory" is not clear to the user and should be handled with context.

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/22075926/171644502-997184d3-2f82-4608-81d7-35012e8e3888.png">

**Comment by ueno** [comment]
Is the `NotFound` error really about EK cert? There is a "No EK certificate found in TPM NVRAM" message in the log and I think the agent itself should be able to run without it (as tested in #214).

**Comment by lkatalin** [comment]
Thanks @ueno , not sure yet if it's the EK cert so that's helpful as we investigate the error.

**Comment by lkatalin** [comment]
Thank you @THS-on ! Yes, I think so too now. This seems to be the same problem we had with running `keylime/keylime` CI tests with the Rust agent.
