### ISSUE TITLE
IMA emulator to support IMA signatures

### ISSUE THREAD

**Issue by kkaarreell** [keylime/rust-keylime#393]
Having that would enable us to run IMA signatures related tests in CI.

**Comment by kkaarreell** [comment]
Maybe I got confused and configuring kernel accordingly would be enough.

**Comment by ueno** [comment]
No, the current Rust implementation lacks support for IMA signatures; I plan to enable it as part of #376.

**Comment by ueno** [comment]
Should be fixed now in #376.
