### ISSUE TITLE
Return type update in tpm.rs

### ISSUE THREAD

**Issue by leonjia0112** [keylime/rust-keylime#40]
Some of the functions have return type option/bool/string in tpm.rs that all need to be updated to Result for error handling. You can assign this issue to me, I will do this in the future PR.

**Comment by leonjia0112** [comment]
Follow up for this issue, I am thinking about using a single custom error type to wrap around all the errors in tpm.rs and make it as a return type for all the functions in tpm.rs.

The custom error type contains two fields as showing
```rust
{
    code: i32,
    details: String,
}
```
error code are used for distinguishing error type, for example
error code 5 representing the TPM_IO_ERROR
error code 10 representing the std::io::Error

Seeking comment for this implementation.

**Comment by mbestavros** [comment]
> error code are used for distinguishing error type, for example
> error code 5 representing the TPM_IO_ERROR
> error code 10 representing the std::io::Error

@leonjia0112 I don't think we need to hide Rust-specific errors like `std::io::error` behind an error code, especially when we already need to deal with error codes from the TPM like `TPM_IO_ERROR`. Mixing Rust errors in seems like a sure-fire way to confuse developers later down the road.

Instead, I think we should consider multiple error subtypes, wrapped up in one master Error type for the whole file -- [much as I did](https://github.com/keylime/rust-keylime/blob/c4c1d33629e0b3911d45a16bc2c5134bc76cc8e5/src/crypto.rs#L118) in `crypto.rs` for #42. This affords us some nice granularity around how much detail we want to inherit from upstream errors like the ones you mention -- for example, TPM errors can include their error code, but basic Rust errors only need to include a basic description.

Here's a basic example of what I'm thinking:

```
enum KeylimeTPMError {
    RustError { details : string }
    TPMError {
        code: i32,
        details: String,
    }
}
```

Though this is all still part of one big error type, we can still refer to each individually using (for example) `KeylimeTPMError::RustError` or `KeylimeTPMError::TPMError`.

Just my two cents, and definitely open to thoughts or improvements.

**Comment by leonjia0112** [comment]
This looks like a reasonable way to do this. Thank you so much for your suggestion.
Because a single error type with error code representing the error source I feel like it is just adding redundant information to it that makes it more complicated.

Do you mind reviewing the RP#28 as well once I update it?

**Comment by mbestavros** [comment]
Of course, just ping me when it's ready.
