### ISSUE TITLE
TPM quote decoding fails on s390x arch

### ISSUE THREAD

**Issue by ansasaki** [keylime/rust-keylime#407]
When packaging `rust-keylime` on Fedora, the build on s390x machine fails when running the `tpm::quote_encode_decode` test:

```
failures:
---- tpm::quote_encode_decode stdout ----
thread 'tpm::quote_encode_decode' panicked at 'unable to decode quote: Tpm { err: WrapperError(InvalidParam), kind: None, message: "the provided parameter is invalid for that type." }', src/tpm.rs:871:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    tpm::quote_encode_decode
test result: FAILED. 36 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.80s
     Running `/builddir/build/BUILD/rust-keylime-aed51c7c8c526953e945357594352c3df2ca4ace/target/release/deps/keylime_ima_emulator-3020e777b56dff63`
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
error: test failed, to rerun pass '--bin keylime_agent'
error: Bad exit status from /var/tmp/rpm-tmp.qeHIOg (%check)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.qeHIOg (%check)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.10/site-packages/mockbuild/util.py", line 598, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
```

The culprit seems to be the following `std::mem::transmute` call:
https://github.com/keylime/rust-keylime/blob/25a5ddd2c22ec6201368b0c8c30047f547c60243/src/tpm.rs#L677-L681

Quoting the rust documentation on [transmutes](https://doc.rust-lang.org/stable/nomicon/transmutes.html#transmutes):
> Get out of our way type system! We're going to reinterpret these bits or die trying! Even though this book is all about doing things that are unsafe, I really can't emphasize that you should deeply think about finding Another Way than the operations covered in this section. This is really, truly, the most horribly unsafe thing you can do in Rust. The guardrails here are dental floss.

The probable cause of the issue is the endianness of the s390x arch, which is big endian, making the contents of the structures to be misinterpreted when "decoding". The `std::mem::transmute` usage should be avoided, if possible.

**Comment by ueno** [comment]
My random guess is that, some fields in the `TPMS_PCR_SELECTION` and `TPM2B_DIGEST` are not properly converted to little endian before serializing, as in:
- https://github.com/tpm2-software/tpm2-tools/blob/9cf075b8f8563a75b465e06a428c962e6ef83fd1/lib/pcr.c#L246
- https://github.com/tpm2-software/tpm2-tools/blob/9cf075b8f8563a75b465e06a428c962e6ef83fd1/lib/pcr.c#L272
