### ISSUE TITLE
Fail during the actiave crendial stage

### ISSUE THREAD

**Issue by aplanas** [keylime/rust-keylime#413]
Using the verifier / register from 6.4.1 and the HEAD rust-keylime agent, I have this error during the activate credential stage:

```
INFO  keylime_agent::registrar_agent > Requesting agent registration from http://10.162.233.246:8890/v2.0/agents/343e11c2-03db-426c-b502-7ac389129ddc for 343e11c2-03db-426c-b502-7ac389129ddc
WARNING:esys:src/tss2-esys/api/Esys_ActivateCredential.c:321:Esys_ActivateCredential_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_ActivateCredential.c:105:Esys_ActivateCredential() Esys Finish ErrorCode (0x000001df) 
Error: Tpm { err: Tss2Error(FormatOne(FormatOneResponseCode { .0: 479, error_number: 31, parameter: true, format_selector: true, number: 1 })), kind: Some(Integrity), message: "integrity check failed (associated with parameter number 1)" }
```

This happens in the last section of `activate_credential`:

```rust
    let resp = ctx
        .execute_with_sessions(
            (Some(AuthSession::Password), Some(ek_auth), None),
            |context| context.activate_credential(ak, ek, credential, secret),
        )
        .map_err(KeylimeError::from);
```

**Comment by lkatalin** [comment]
> Can you try `tpm2_clear` before launching the agent?

I wonder if the Rust agent should be able to do `tpm2_clear` (maybe with some interactive warning about whether you want to proceed) since it comes up so often.

**Comment by THS-on** [comment]
It is probably because Keylime sets the owner auth, but there might be something else that was not cleaned up. Doing a `tpm2_clear` is like using a big hammer to solve the problem. It probably works but is not ideal.

**Comment by lkatalin** [comment]
> It is probably because Keylime sets the owner auth, but there might be something else that was not cleaned up. Doing a `tpm2_clear` is like using a big hammer to solve the problem. It probably works but is not ideal.

Hmm, perhaps just a documentation task then. As a note, the Rust agent won't set the owner auth anymore so this shouldn't be a problem eventually (except maybe incidentally in the system environment).

**Comment by aplanas** [comment]
> Can you try `tpm2_clear` before launching the agent?

Sorry for the delay. Seems that this is not the issue:

```
# tpm2_clear
# RUST_LOG=keylime_agent=trace ./keylime_agent
 WARN  keylime_agent::common > Agent Data not available under: /var/lib/keylime/agent_data.json
 WARN  keylime_agent::common > Cannot drop privileges since 'run_as' is empty or missing in 'cloud_agent' section of keylime.conf.
 DEBUG keylime_agent::secure_mount > Secure store location /var/lib/keylime/secure already mounted on tmpfs
 INFO  keylime_agent               > Starting server with API version v2.0...
 WARN  keylime_agent               > INSECURE: Keylime is using a software TPM emulator rather than a real hardware TPM.
 WARN  keylime_agent               > INSECURE: The security of Keylime is NOT linked to a hardware root of trust.
 WARN  keylime_agent               > INSECURE: Only use Keylime in this mode for testing or debugging purposes.
 INFO  keylime_agent               > Agent UUID: 343e11c2-03db-426c-b502-7ac389129ddc
 INFO  keylime_agent::registrar_agent > Requesting agent registration from http://10.162.233.246:8890/v2.0/agents/343e11c2-03db-426c-b502-7ac389129ddc for 343e11c2-03db-426c-b502-7ac389129ddc
 INFO  keylime_agent                  > SUCCESS: Agent 343e11c2-03db-426c-b502-7ac389129ddc registered
WARNING:esys:src/tss2-esys/api/Esys_ActivateCredential.c:321:Esys_ActivateCredential_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_ActivateCredential.c:105:Esys_ActivateCredential() Esys Finish ErrorCode (0x000001df) 
Error: Tpm { err: Tss2Error(FormatOne(FormatOneResponseCode { .0: 479, error_number: 31, parameter: true, format_selector: true, number: 1 })), kind: Some(Integrity), message: "integrity check failed (associated with parameter number 1)" }
```

**Comment by aplanas** [comment]
I am trying to debug this issue, but I am hitting some walls in my understanding.

So far I have a dump of the `tpm2_makecredential` generated by the registrar, and I de-serialized the `ak_public` and `ak_private` that is living in `agent_data.json`.

In this step I see something weird, and is that the `ak_private` size is 222 bytes, but when I generate the AK via `tpm2_createak`, or a key via `tpm2_create`, the private pars is always 224 (the public part match with 280 in all cases).

I can generate a `primary.ctx` with `tpm2_createek`, and I can see that the public part of the EK key match correctly.  But now I am blocked on loading the AK with `tpm2_load` using this EK primary context as a parent parameter (`-C`)

**Comment by THS-on** [comment]
> In this step I see something weird, and is that the ak_private size is 222 bytes, but when I generate the AK via tpm2_createak, or a key via tpm2_create, the private pars is always 224 (the public part match with 282 in all cases).

The difference is probably because the rust agent stores the bytes returned by the TPM directly and the tools marshall it before dumping it to disk. My guess is that the two bytes at the start are just the length of the structure.

**Comment by aplanas** [comment]
> length of the structure

You are correct! 0xde == 222. I also realized that was indeed missing the length in the public part too. I added manually and I have "authValue or authPolicy is not available for selected entity" error. That is an advance. Thanks!

**Comment by aplanas** [comment]
Ok. The bug is in tpm2.0-tools when enabling LTO. The good news is that this seems to be fixed in HEAD, the bad news is that why I only see this bug in the Rust agent, and not in the Python one.

I will check why this is not present in the Python one, to check if there is some other issue hidden, but for now lets close this.
