### ISSUE TITLE
Specify config file relationships between Python and Rust

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#418]
I think I've already had discussion on this with @ansasaki and @mpeters , but I don't remember the outcome. The `keylime.conf` files in `keylime/keylime` and in this repo are different and there is not a clear process for keeping them synced up. Moreover, it is unclear to me if the conf file from the Rust repo is ever used (unless our `makefile` pulls this in, but I did not see it). Ideally, the conf should be one file, ex. in a `keylime/config` repo, that could be pulled in by both Python and Rust components. What do you all think, or was there a different plan that I am forgetting?

**Comment by THS-on** [comment]
Part of https://github.com/keylime/enhancements/pull/73 is allowing the configuration files of the Python and Rust code to diverge. It does not make sense to keep many of the old options for the agent because the Rust agent solves it differently and most of the configuration (e.g. registrar, verifier, tenant parts) is not relevant for the agent.

Also Python supports their INI format really well, but for the Rust code it is probably beneficial to use somthing like TOML which is supported by serde.

**Comment by lkatalin** [comment]
Great, I will read through this today. Thanks!

**Comment by lkatalin** [comment]
Thanks for pointing me to that enhancement @THS-on , looks like there are a lot of positive changes planned. I don't yet understand how the divergent configs will be reconciled with or without the enhancement, though. Once the Rust agent is "official" will the (potentially new, agent-specific as described in the enhancement) config from the Rust repo replace the (agent-specific) Python config in the main Keylime repo?

**Comment by THS-on** [comment]
They will not replace each other, they will be completely different configurations all together. This means if one system had the Python agent installed the Rust agent will not try to load the old configuration and vice versa. To make this more clear the rust agent we can rename the rust agent configuration to something like `keylime-agent.conf`.

**Comment by lkatalin** [comment]
I assume the Python config will not be needed / supported once the Python agent is deprecated? It is only in the overlap between the two agents that we would need to make sure the conf names are different.

I think my question is more around the fact that currently running `./installer.sh` installs the [Python conf](https://github.com/keylime/keylime/blob/master/keylime.conf) to `/etc/keylime.conf` but the [Rust conf](https://github.com/keylime/rust-keylime/blob/master/keylime.conf) is not currently used at all, unless I am missing something. Will the enhancement bring some of the changes from the Rust conf into the main Keylime repo?

**Comment by THS-on** [comment]
> I assume the Python config will not be needed / supported once the Python agent is deprecated? 

Correct. The Python config for the agents will be removed once the it is no longer needed.

> [...] but the [Rust conf](https://github.com/keylime/rust-keylime/blob/master/keylime.conf) is not currently used at all, unless I am missing something.

You are correct that the current configuration is not used by default if `KEYLIME_CONFIG` is not set to another location. We should probably make it part of the Makefile and the package should ship the version from this repo. 

The Python conf location will be changed with the proposal to `/usr/etc/keylime/{verifier,registrar,tenant,agent}.conf` and I don't expect most systems to have both agents installed (outside of testing).

**Comment by lkatalin** [comment]
> We should probably make it part of the Makefile and the package should ship the version from this repo.

Great, this makes sense. I'll leave this issue open with these as the action items.

**Comment by greyspectrum** [comment]
@THS-on When you say that the config should be made a part of the Makefile, do you mean that the Rust [config file](https://github.com/keylime/rust-keylime/blob/master/keylime.conf) should be copied to `/etc/keylime.conf` in the Makefile, so that it gets set as the default, [here](https://github.com/keylime/rust-keylime/blob/f8a5941ed17d3b7a3f3118fac6af3722fdd12211/src/common.rs#L40)?

**Comment by THS-on** [comment]
Yes, `make install` should copy the config to `/etc/`. I would also rename the `keylime.conf` to `keylime-agent.conf`, so that it cannot be confused with the Python agent configuration.

**Comment by lkatalin** [comment]
I think we can close this since we have made changes to the config files in both repos per the enhancement.
