### ISSUE TITLE
Own error type

### ISSUE THREAD

**Issue by leonjia0112** [keylime/rust-keylime#42]
Would it be better if there is an error type for our own crate that can map from other error? (e.g. From<io::Errror>, etc)

Because now the err handling type is a boxed string, which looks not professional. :)

**Comment by frozencemetery** [comment]
(Per out-of-band conversation, this is a good idea.)

**Comment by lukehinds** [comment]
Likely another one that can be closed (based on the merged PR above)

**Comment by frozencemetery** [comment]
@mbestavros how close are you on this?

**Comment by mbestavros** [comment]
I've got a basic custom error for `crypto.rs` working on my end. I'm currently hashing out the best way to wrap `ErrorStack` errors thrown by `rust-openssl`; once that's done, I'll integrate them into the existing bindings and push for review.

**Comment by mbestavros** [comment]
@frozencemetery and @lukehinds: The above two PRs (#49 and #52) implement a custom error type for `crypto.rs` and adjust the return types of the functions introduced in #43, as specified. Unless we'd like to keep this issue open to encapsulate other potential custom errors elsewhere in the codebase, I think this is fair game to be resolved. 

(Personally, I think it'd make more sense to open separate issues for other custom error types, should we want to pursue them.)

**Comment by frozencemetery** [comment]
Agreed, closing.
