### ISSUE TITLE
Cargo command in makefile does not interact well with permissions

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#420]
Running `cargo` with `sudo` is not recommended and does not work by default, and running `make install` without `sudo` can result in an error if the current user does not have the right permissions for `/usr/bin/` (which is the case for non-root users). This could frustrate a user trying to use the makefile.

```
[f36-keylime@localhost-live rust-keylime]$ make install
cargo build --target-dir="target" 
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
install -D -t /usr/bin "target/debug/keylime_agent"
install: cannot create regular file '/usr/bin/keylime_agent': Permission denied
make: *** [GNUmakefile:25: install] Error 1

[f36-keylime@localhost-live rust-keylime]$ sudo make install
cargo build --target-dir="target" 
/bin/sh: line 1: cargo: command not found
make: *** [GNUmakefile:21: build] Error 127
```

**Comment by ueno** [comment]
As suggested in README.md, the program building and installation are usually done in two steps, first with "make" as a normal user, and then "make install" as root. This currently doesn't work because of missing dependency declarations. I've filed #421.
