### ISSUE TITLE
Test Rust agent with TOML-based config file

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#424]
We want to have this working before `0.1.0`

**Comment by lkatalin** [comment]
This is on the roadmap before we can make the Rust agent official, is anyone planning to work on this currently?

**Comment by ansasaki** [comment]
@lkatalin I'll take this

**Comment by lkatalin** [comment]
> @lkatalin I'll take this

Great, thank you!

**Comment by ansasaki** [comment]
This was fixed by #449
