### ISSUE TITLE
Make use of "tpm_ownerpassword" option for claiming ownership of TPM

### ISSUE THREAD

**Issue by ueno** [keylime/rust-keylime#429]
The Python agent has a mechanism to take ownership of TPM based on a password given with "tpm_ownerpassword", which is basically [implemented](https://github.com/keylime/keylime/blob/8b8d0c60da066bd55fe05e3399d2ea63d3d00652/keylime/tpm/tpm_main.py#L391) as follows:
- try to call `tpm2_changeauth -c o <password>` and `tpm2_changeauth -c e <password>` with the given password
- if it fails, try again with `-p <password>` option to the above command line to check if the ownership is already taken by ourselves
- if it fails, raise an error, as that means other application is using the TPM with a different password

The Rust agent currently doesn't have this logic.

**Comment by ueno** [comment]
@lkatalin feel free to close if this is something we don't want to pursue in Rust agent.

**Comment by THS-on** [comment]
We shouldn't change ownership, because we don't need it for creating the EK. We might add an option to specify a password if another program claimed ownership.

**Comment by lkatalin** [comment]
Yeah, unless something big changed that I'm not aware of, we actively do not want the Rust agent to take TPM ownership as it caused many problems.

**Comment by ueno** [comment]
Thanks for the clarification, let's close this then.
