### ISSUE TITLE
keylime-agent.conf should default to run_as = keylime:tss

### ISSUE THREAD

**Issue by kkaarreell** [keylime/rust-keylime#439]
Rust agent should be dropping privileges by default, making it more secure.
While Python agent has `run_as = ` we should strive for more secure defaults for the rust agent.

**Comment by kkaarreell** [comment]
I am sorry, I got confused by Fedora defaults and falsely assumed that Python agent uses `keylime:tss`. I have therefore updated the issue description.

**Comment by ansasaki** [comment]
This was fixed by #449 
The new default for `run_as` is `keylime:tss`
