### ISSUE TITLE
Agent do not reply with JSON for some endpoints

### ISSUE THREAD

**Issue by ansasaki** [keylime/rust-keylime#447]
The following endpoints do not reply with JSON:

- /keys/ukey
- /keys/vkey
- /quotes/revocation

The keylime/keylime test suite expects to receive back a JSON from all endpoints

**Comment by lkatalin** [comment]
@ansasaki This seems like it would cause the Keylime CI bug?

**Comment by ansasaki** [comment]
It is just one of the issues, unfortunately there are more.

**Comment by lkatalin** [comment]
I see. Let me know if you want any help!

**Comment by ansasaki** [comment]
Closed via #499
