### ISSUE TITLE
Codebase cleanup

### ISSUE THREAD

**Issue by frozencemetery** [keylime/rust-keylime#45]
Between rustfmt's requirements being... bad... and our need to develop quickly, we have accumulated a fair amount of ugliness in the repo already.  Suggestions on how to fix this are welcome, but my guess is we need an actual style document and more than one reviewer on each PR, as well as dropping rustfmt.

**Comment by leonjia0112** [comment]
Indeed, rustfmt doesn't fix up all the style problem. There is an official style guideline [here](https://doc.rust-lang.org/1.0.0/style/README.html), but it looks like still in working progress. More than one reviewer is a good idea.

Once there is a style doc, can we follow the guide style and go through our code base to clean up as much ugly code as we can?

**Comment by lukehinds** [comment]
I will make an effort to review more, been a little busy over on the python side, but we are getting in good order now. I wonder if now might be a good time to migrate the repo over to keylime GitHub org. Charlie and Nabil are regularly reviewing patches and that would be beneficial for the 2.0 port. We can retain the exact same permissions and do a whole sale migration?
