### ISSUE TITLE
Generate tpmdata.json in build time

### ISSUE THREAD

**Issue by leonjia0112** [keylime/rust-keylime#47]
File `tpmdata.json` shouldn't be generated in `cargo build`, because it is
generated by function `set_tpmdata_test()` function in the test suite for
testing purpose. This could cause a potential problem if this file is not
overwritten before the program reads the data inside. 

My guess is let the file to be generated in `cargo test` instead of `cargo build`.

**Comment by ashcrow** [comment]
As of 292c821fcab6c2f8b2720acfa8ba4910ab7cd908 `cargo build` doesn't seem to be generating `tpmdata.json`.

```
$ cargo build
    Updating crates.io index
  Downloaded lock_api v0.3.4
<snip />
warning: 46 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 2m 14s
$ git diff
$ find . -name "tpmdata.json"
$
```

After running the test suite with `cargo test` I do see a generated `tpmdata.json` file in the project root that was generated. Based on the text of the issue listed here I think this can be closed.
