### ISSUE TITLE
modernize vTPM support

### ISSUE THREAD

**Issue by leonjia0112** [keylime/rust-keylime#48]
vTPM is not implemented in TPM2.0. Consider removing create_deep_quote() function.

**Comment by lukehinds** [comment]
Hi @leonjia0112 

It might not be at present, but we are looking to implement this with the vTPM support now in QEMU:

Under that premise I recommend we keep this function for now, although it might well need some changes in time.

https://github.com/keylime/python-keylime/issues/29
