### ISSUE TITLE
Environment override does not work if option cointains "_"

### ISSUE THREAD

**Issue by THS-on** [keylime/rust-keylime#510]
For example `KEYLIME_AGENT_CONACT_IP` does nothing.

This is a known problem in the `config-rs` module: https://github.com/mehcode/config-rs/issues/391

The suggestion is to use another separator, e.g double underscores or: `KEYLIME__AGENT__CONACT_IP`

**Comment by THS-on** [comment]
@aplanas @ansasaki any ideas on how to fix this nicely?

**Comment by ansasaki** [comment]
@THS-on Yeah, this is bad and I don't see a clean way to make it not ambiguous for the library. We would need to make the separator something that is prohibited to be used when naming the configuration options. The least ugly options I see are:

* Dots (e.g. `KEYLIME.AGENT.CONTACT_IP`)
* Double underscores (e.g. `KEYLIME__AGENT__CONTACT_IP`)

@maugustosilva FYI, it seems we have a bug related with overriding the configuration with environment variables.

**Comment by ansasaki** [comment]
Another option would be if we modified the internal configuration struct to not have 2 levels and makes the whole `KEYLIME_AGENT_` the prefix. Then we set the separator to be anything other than `_` and it should work.

Currently the struct is something like:

- Keylime
  -  agent
     - contact_ip 
     
We would need to change it to:

- Keylime_agent
  - contact_ip

**Comment by THS-on** [comment]
The question is if we want to support nested levels or not. I don't have a big opinion about it as long as the feature works.

**Comment by ansasaki** [comment]
> The question is if we want to support nested levels or not. I don't have a big opinion about it as long as the feature works.

It is not just a question of nested levels, but a decision to change the configuration file itself. Currently, to make it closer to the python agent configuration, the configuration for the rust side needs all the fields to be in the `[agent]` section. With the change I proposed above it would need a change in the configuration file to drop the `[agent]` section completely (meaning that we need another version for configuration files and respective templates for upgrades)

**Comment by mpeters** [comment]
I like the idea of dropping the `[agent]` section (of course we'd need to support backwards compat, but that backwards compat doesn't need to support env overrides since those don't work anyway). I don't think anything about the agent would need nested sections.

**Comment by THS-on** [comment]
@mpeters this has also the advantage to make it also consistent with the server side, so it is probably the best approach.

**Comment by ansasaki** [comment]
I have a working solution that does not require any change to the configuration file nor to the environment variables format.  The solution is to read the environment configuration separately and then use these values to override what was obtained from the configuration files.
