### ISSUE TITLE
Update reviewers required for merge

### ISSUE THREAD

**Issue by lkatalin** [keylime/rust-keylime#515]
@lkatalin to do this if it is not done already.

**Comment by kkaarreell** [comment]
Not me please, don't know a thing about Rust.

**Comment by lkatalin** [comment]
> Not me please, don't know a thing about Rust.

Okay, no problem. :)

**Comment by lukehinds** [comment]
sgtm, should I go ahead and do this, or do you want to let it hang for a few days?

**Comment by lkatalin** [comment]
> sgtm, should I go ahead and do this, or do you want to let it hang for a few days?

Thanks @lukehinds , let's wait until EOD Monday in case people want to update the list. I can ping you about it.

@mpeters said he updated some permissions to resolve the immediate problem - thanks! (Though I'm not sure where the perms were changed - long-term it seems best to keep this all together in the `rust-team` IMO).

**Comment by aplanas** [comment]
I will be very happy to help

**Comment by lkatalin** [comment]
@sergio-correia has also asked to be added, so we can move forward with adding @sergio-correia @aplanas @THS-on to the `rust-team` whenever you are able to do so, @lukehinds or @mpeters . Thanks!

**Comment by mpeters** [comment]
Done
