### ISSUE TITLE
TPM2.0 testing environment in CI

### ISSUE THREAD

**Issue by leonjia0112** [keylime/rust-keylime#55]
How about setting up the CI environment to allow it have a TPM2.0 environment alongside w/ software TPM2 so the testing suite can run those TPM 2.0 commands?

I have a short script [tpm2-setup](https://github.com/leonjia0112/tpm2-setup) for Fed 29 that can deploy TPM2.0 w/ software TPM2, which is what I am using for testing.

@frozencemetery @lukehinds @mbestavros

**Comment by lukehinds** [comment]
Unfortunately the script will not work with travis as there are no Fed 2X vm's, you would instead need to spawn a container, as they only provide ubuntu VM's. 

sounds like you would like to do some functional tests than unit tests (if you need a simulator)? 

I added this as a topic to the next meeting, with the view of making CI x-project (with python-keylime), ultimately we want to sure that that any changes in py-keylime do not break rust-keylime and vice versa. In fact, once TPM 2.0 lands in rust, we also need to consider how mature the rust-node is and can it start moving towards being the default keylime node implementation over time, or even what do we need to do to satisfy ourselves the needed criterion is met for it to be considered mature or robust enough.

Going back to CI, I have docker files we can use that will (in a hacky way) run systemd (needed for dbus and tpm2-abrmd).

**Comment by leonjia0112** [comment]
Docker might be a more ideal solution for our case in Travis CI testing against TPM2.0 w/ simulator. I would definitely try this out. The Dockerfile you mentioned, is this the docker file in the py-keylime repo? [link](https://github.com/keylime/python-keylime/tree/master/docker). 

Also agreed with what you just said, ultimately, a CI environment that is able to ensure the robustness of both py-keylime and rust-keylime should be the goal one way or the other.

**Comment by lukehinds** [comment]
Those are the ones.

Are you using a tpm 1.2 simulator anywhere in the current tests running in travis? From a quick look I could not see anything (I think it's mainly assert using dummy data from `tpmdata_test.json`)? 

For the docker stuff, by all means have a play, but don't worry about implementing anything yet, we first need to talk this over and think about what we want our testing to look at going forwards into the projects future.

**Comment by leonjia0112** [comment]
Actually, there isn't any TPM module in the CI currently. The test suite is made to force pass while TPM is not found. I think this worth talk a little bit in the next meeting.
