### ISSUE TITLE
Update of required dependencies

### ISSUE THREAD

**Issue by Doctor-love** [keylime/rust-keylime#622]
This may be more of a question than an issue - apologies in advance!

The README states that the following Fedora packages are required for build and **runtime**:

- openssl-devel
- gcc
- tpm2-tss-devel
- zeromq-devel
- libarchive-devel

As of version 0.2.2, is this still true? Do agents really need GCC during runtime?

**Comment by ansasaki** [comment]
> This may be more of a question than an issue - apologies in advance!
> 
> The README states that the following Fedora packages are required for build and **runtime**:
> 
>     * openssl-devel
> 
>     * gcc
> 
>     * tpm2-tss-devel
> 
>     * zeromq-devel
> 
>     * libarchive-devel
> 
> 
> As of version 0.2.2, is this still true? Do agents really need GCC during runtime?

No, GCC is not required in runtime. It seems we have not been diligent updating the requirements in README file, sorry about that.

**Comment by Doctor-love** [comment]
Does it require the devel version of the other packages after build? Seems a bit odd, but mayhaps I'm missing something about how the FFI works.

**Comment by ansasaki** [comment]
> Does it require the devel version of the other packages after build? Seems a bit odd, but mayhaps I'm missing something about how the FFI works.

It does not require the devel packages after build.

**Comment by ansasaki** [comment]
Please check if #624 makes it clear.

**Comment by Doctor-love** [comment]
Indeed it does! Thanks for your work on this issue, @ansasaki .
