### ISSUE TITLE
Using tpm2-tss rather than tpm2-tools

### ISSUE THREAD

**Issue by jhand2** [keylime/rust-keylime#74]
Do folks have thoughts on using tpm2-tss rather than tpm2-tools? Currently TPM 2.0 interactions rely on calls the the tpm2-tools command line utilities which requires storing state in local files and launching a new process for every TPM interaction.

It may instead make more sense to have rust bindings for the tpm2-tss C libraries (in a separate repo probably. It seems like there may be some people on github who have taken a shot at this already) and then call those.

I understand this is more commitment to build and/or maintain bindings to the libraries, but I'm curious if there is long-term interest here.

**Comment by lukehinds** [comment]
Hi Jordan!

I am certainly not opposed, and it make a lot of sense with how you outline the economy of each call. The use of wrapping around the tools, comes from the previous approach in the python agent (which will eventually be depreciated and replaced by the rust agent (aka this repo)). 

> I understand this is more commitment to build and/or maintain bindings to the libraries, but I'm curious if there is long-term interest here.

I think the key element will be nailing down what extra benefits we will gain, that are missing with the current approach. keylime is not a very resource intensive tool for towards the tpm, after we set up the initial boostrapping around ownership and creating various keys, we start to periodically poll `tpm2_quote`.

I am going to tag @jetwhiz and @nabilschear who know the stack better than myself.

Coincidentally, nice to have you hear. Do you have an interest in using keylime or perhaps making contributions. If so, feel free to open issues as questions or you can also reach us in our [gitter  chat channel](https://gitter.im/keylime-project/community)

Luke

**Comment by frozencemetery** [comment]
I'm not opposed to it - it is a question of priorities though.  In general I agree the non-forking model would be superior, but I don't want to let the perfect be the enemy of the good, and right now we don't have a full set of bindings at all.

**Comment by jhand2** [comment]
Thanks for the quick response Luke! I've done quite a bit of work with attestation and TPMs in the past and think an open attestation project is intriguing in terms of getting this technology out to a lot more people. Plus I have an interest diving more into rust. I don't know how much time I'll have to devote right now but I'm definitely interested in contributing.

In terms of this work, I totally agree that getting a fully functional rust client (with parity to the python version) should be priority.

Long term, I think the benefit of doing this work is as follows:
* Calling the libraries gives a clear interface to the TPM and allows you make use of rust types to manage state and pass parameters more easily
* In my experience people want security but never at the expense of performance. I know the current performance hit may not be too bad but using as few system resources as possible lowers the barrier to entry for new users
* Managing state in files can be a little fragile. Especially for short-lived state keeping everything in memory is more robust

Some challenges:
* You would really want full bindings for rust to tpm2-tss (not just the functions you're using right now). This takes time. Looks like there's something on github but its not maintained.
* Would this need to be done from tpm1.2 libraries as well? Probably. If so, thats more time.

Ultimately I think its something to shoot for long term but understand it may be a lot of work now for an unknown reward in performance. If I get some more time in the next couple weeks I may even look into taking on a piece of this.

**Comment by frozencemetery** [comment]
> Would this need to be done from tpm1.2 libraries as well? Probably. If so, thats more time.

I strongly recommend not doing that.  TPM-1.2 only provides SHA-1, which cannot provide the security guarantees users will expect.  We shouldn't be building new code against it.

**Comment by lukehinds** [comment]
> You would really want full bindings for rust to tpm2-tss (not just the functions you're using right now). This takes time. Looks like there's something on github but its not maintained.

I guess it would make sense to prioritise what we need first, and others can be extended as per need. We do have some other calls we would like to get working upstream (deep attestation), that would then be extended into rust bindings (if we go that route). 

> Would this need to be done from tpm1.2 libraries as well? Probably. If so, thats more time.

Agree with @frozencemetery here, sha1 is insecure and TPM 1.2 is really legacy now. We made a decision to drop 1.2 support in the rust implementation.

**Comment by hug-dev** [comment]
Hello!
I was reading through your repository and came up on this issue after seeing the `src/tpm.rs` file. As part of the Parsec project, we developped a TPM2.0 ESYS API crate available [here](https://github.com/parallaxsecond/rust-tss-esapi). It is in the early stages and we do not support all APIs but it is in active development! It looks like something that could be used by your project as well, if we already support the features that you want but if not, we would be happy to see how we could!

**Comment by lukehinds** [comment]
That's awesome, thanks @hug-dev . So at the moment development of our rust agent has stalled, but its only parked, not dropped, so this would make a lot of sense to use (TPM2.0 ESYS API crate ) once we pick things up again (which should be soon). 

I also heard about the Parsec project recently as well, exciting tech. I heard about you from your cncf proposal. Let's keep in touch!

**Comment by lukehinds** [comment]
going to close this issue as work is underway and tracked here: https://github.com/keylime/rust-keylime/issues/89
