### ISSUE TITLE
Implement Rust TSS ESAPI

### ISSUE THREAD

**Issue by lukehinds** [keylime/rust-keylime#89]
Work within the [Rust TSS ESAPI](https://github.com/parallaxsecond/rust-tss-esapi) project to implement all functionality TPM required by Keylime Agent

Current commands used:

- [x] ~~`tpm2_startup`~~ ([PR](https://github.com/parallaxsecond/rust-tss-esapi/pull/133))
- [x] ~~`tpm2_changeauth`~~ ([PR](https://github.com/parallaxsecond/rust-tss-esapi/pull/162))
- [x] `tpm2_getcap`
- [x] `tpm2_nvread`
- [ ] `tpm2_deluxequote`
- [x] `tpm2_quote`
- [ ] `tpm2_checkquote`
- [x] `tpm2_evictcontrol` ([PR](https://github.com/parallaxsecond/rust-tss-esapi/pull/146))
- [x] `tpm2_createek` ([PR](https://github.com/parallaxsecond/rust-tss-esapi/pull/139))
- [x] `tpm2_createak` ([PR](https://github.com/parallaxsecond/rust-tss-esapi/pull/166))
- [x] `tpm2_readpublic`
- [x] `tpm2_makecredential` ([PR](https://github.com/parallaxsecond/rust-tss-esapi/pull/158))
- [x] `tpm2_activatecredential` ([PR](https://github.com/parallaxsecond/rust-tss-esapi/pull/158))
- [x] `tpm2_startauthsession`
- [x] `tpm2_policysecret` ([PR](https://github.com/parallaxsecond/rust-tss-esapi/pull/161))
- [x] `tpm2_flushcontext`
- [x] `tpm2_pcrreset` ([PR](https://github.com/parallaxsecond/rust-tss-esapi/pull/131))
- [x] `tpm2_pcrextend` ([PR](https://github.com/parallaxsecond/rust-tss-esapi/pull/131))
- [x] `tpm2_pcrread`
- [x] `tpm2_getrandom`
- [x] `tpm2_nvdefine`
- [x] `tpm2_nvwrite`
- [x] `tpm2_nvlist` ([PR](https://github.com/parallaxsecond/rust-tss-esapi/pull/150))
- [x] `tpm2_nvreadpublic`

**Comment by puiterwijk** [comment]
The `pcr_reset` and `pcr_extend` functions are at https://github.com/parallaxsecond/rust-tss-esapi/pull/131.

**Comment by puiterwijk** [comment]
At this moment, all the functions that we require have been merged into `rust-tss-esapi`!
The two remaining ones are very high-level and technically already there (just different names).
