### ISSUE TITLE
Implement HTTP server GET / POST

### ISSUE THREAD

**Issue by lukehinds** [keylime/rust-keylime#91]
A HTTP server is required with GET / POST handlers for communications with the Registrar and the Verifier.

**Comment by lkatalin** [comment]
@lukehinds Is this one resolved? We have communication with the registrar and verifier as of #158 .

**Comment by lkatalin** [comment]
And also #134

**Comment by lukehinds** [comment]
yep, we can close this now as we have the handlers stubbed out.
