### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by lukehinds** [keylime/rust-keylime#94]
Alongside unit tests, we need some form of functional / Integration tests, where we test core functionality against the Keylime registrar and verifier.

**Comment by lkatalin** [comment]
Here are four commands that are a good baseline for testing:

### “base” node identity
`keylime_tenant -c update -t 127.0.0.1 -v 127.0.0.1 -u d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --no-verifier-check --cert /var/lib/keylime/ca/d432fbb3-d2f1-4a97-9ef7-75bd81c00000`

### “base” + measured boot
`keylime_tenant -c update -t 127.0.0.1 -v 127.0.0.1 -u d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --no-verifier-check --cert /var/lib/keylime/ca/d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --mb_refstate /root/mb_refstate.txt`
where `mb_refstate.txt` can contain just `{}`

### “base” + measured boot + IMA
`keylime_tenant -c update -t 127.0.0.1 -v 127.0.0.1 -u d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --no-verifier-check --cert /var/lib/keylime/ca/d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --mb_refstate /root/mb_refstate.txt --allowlist /root/allowlist.txt --exclude /root/excludes.txt`

### “base” + measure boot + IMA + autorun
`keylime_tenant -c update -t 127.0.0.1 -v 127.0.0.1 -u d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --no-verifier-check --cert /var/lib/keylime/ca/d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --mb_refstate /root/mb_refstate.txt --allowlist /root/allowlist.txt --exclude /root/excludes.txt --include /root/senddir`
where `senddir` is a (non-zipped) directory containing, for example, some script `autorun.sh`

**Comment by THS-on** [comment]
> Which of the custom tests do we want to run as part of the Rust agent CI most urgently?

1. code style and compile tests
2. Unit tests
3. SP integration tests to see that nothing got broken
4. Basic automatic security analysis (e.g. cargo audit, are there tools like CodeQL for Rust?)

>  What do we want to see from integration testing in the near future?

The agent are rather simple in comparison to the server side, so the main check for the integration tests is to see if the interactions to the server side are not broken.

>  Are we planning to leave the Rust agent repo as a standalone repo after it is the official agent (moving it could potentially give it access to more CI / tests)?

I would leave it in a standalone repository.

**Comment by lkatalin** [comment]
> > Which of the custom tests do we want to run as part of the Rust agent CI most urgently?
> 
>     1. code style and compile tests

We have this already unless you are thinking of something specific? There are some tweaks being made, ex. (https://github.com/keylime/rust-keylime/pull/372).

>     2. Unit tests

Agree, we should aim for more coverage. We could try to get everything into the "green" category with `cargo-tarpaulin` (looks like that's 80 or 85%+ for each path).

>     3. SP integration tests to see that nothing got broken

Yes. From @ansasaki 's comment it looks like this is covered with the Packit-CI testing. :+1: 

>     4. Basic automatic security analysis (e.g. cargo audit, are there tools like CodeQL for Rust?)

Very good idea, we should include `cargo audit`. I'm surprised I didn't find CodeQL support or similar for Rust. The most similar things I can see are general [Github code scanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning) and [clippy-serif](https://crates.io/crates/clippy-sarif). I can look / ask around more.

> The agent are rather simple in comparison to the server side, so the main check for the integration tests is to see if the interactions to the server side are not broken.

+1, I think we would get this from the `keylime/keylime tests`

**Comment by lkatalin** [comment]
> The Packit tests execute tests from RH SP for every PR on CentOS and Fedora. Do you want to run in some different environment using GHA? Is there some specific need that is not covered by the Packit tests?

Thanks for pointing this out. I missed that it brings in all the relevant tests already. Thanks for adding those.


> Which extra tests would we get? I don't see a clear benefit from moving the repo for now.

Sounds good, it looks like consensus is around leaving the repo as standalone. The extra tests I'm thinking of are the ones that run in `keylime/keylime`.

@ansasaki You had also mentioned some friction in the testing process ex. as it relates to the measured boot regression. Is there something missing that would help your workflow or was that addressed when you added the Packet CI tests?

**Comment by lkatalin** [comment]
Comment to track testing-related todos based on above comments:

- [ ] Increase `cargo tarpaulin` coverage of all paths to 85%+
- [ ] Add `cargo audit`
- [ ] Optional: Possibly add something similar to CodeQL, if it exists
- [ ] Bring in `keylime/keylime` tests to Rust agent CI to make sure no changes to the Rust agent are incompatible with the server-side code and APIs
- [ ] Make sure there is at least one test going through the full attestation flow
- [ ] Try to replicate something close to IBM's environment, or at least run all the commands they are using with the options they are using during CI testing

@THS-on @ansasaki Let me know if that sounds about right.

**Comment by ansasaki** [comment]
> @ansasaki You had also mentioned some friction in the testing process ex. as it relates to the measured boot regression. Is there something missing that would help your workflow or was that addressed when you added the Packet CI tests? Edit: I suppose transferring some of IBM's environment to a publicly accessible one would help.

One of the issues was covered by Karel by adding a minimal test for measured boot using a fake file. Transferring some of IBM's environment to be publicly accessible would definitely help, but I don't know how easy would be to integrate that into the CI. It would be great if we had tests using real hardware.

> @THS-on @ansasaki Let me know if that sounds about right.

I think the list is ok. I like the idea of adding the `cargo audit` action, that is important. I saw the report from [deps.rs](https://deps.rs/repo/github/keylime/rust-keylime) that made me think we should track vulnerabilities more closely.

One question is about "Make sure there is at least one test going through the full attestation flow": in my point of view, the tests from RH SP covers this already, what you see missing there?

**Comment by THS-on** [comment]
> One question is about "Make sure there is at least one test going through the full attestation flow": in my point of view, the tests from RH SP covers this already, what you see missing there?

Yes this is covered by the RH SP e2e tests. Also besides running on bare metal hardware those tests cover most of the IBM test suite, if I remember correctly. @kkaarreell do you have there more information what they are testing and you are not?

**Comment by kkaarreell** [comment]
No, I don't know what scenarios are covered by IBM testsuite.

**Comment by THS-on** [comment]
@galmasi @maugustosilva can you briefly describe what you are testing?

**Comment by mpeters** [comment]
. It would be great if we had tests using real hardware.

AWS and GCP now have TPMs that can be tied to cloud compute nodes. It's not quite a discrete TPM chip, but it is real hardware. @kkaarreell might know, but how difficult would it be to incorporate a VM from one of those providers? I know it's not the same as re-using an existing pool of hardware we already own, but are any other projects doing something similar?

**Comment by lkatalin** [comment]
@ansasaki 

> I saw the report from [deps.rs](https://deps.rs/repo/github/keylime/rust-keylime) that made me think we should track vulnerabilities more closely.

Thanks, I added this to the list as well.

> One question is about "Make sure there is at least one test going through the full attestation flow": in my point of view, the tests from RH SP covers this already, what you see missing there?

I didn't realize that, but that's great news. : ) Then we don't need a separate test for this, and I would just want to bring in `keylime/keylime` tests.

**Comment by lkatalin** [comment]
@mpeters 

> AWS and GCP now have TPMs that can be tied to cloud compute nodes. It's not quite a discrete TPM chip, but it is real hardware. @kkaarreell might know, but how difficult would it be to incorporate a VM from one of those providers? I know it's not the same as re-using an existing pool of hardware we already own, but are any other projects doing something similar?

Thanks for proposing this, I agree and we should look into these questions if someone does not already know. The internship project will almost certainly cover some of this work, which hopefully we can at least adapt into the test flow.

**Comment by kkaarreell** [comment]
No, these are not in the plan
https://github.com/RedHat-SP-Security/keylime-tests/blob/main/plans/rust-keylime-tests.fmf
I didn't even try it myself. But IMO e2e tests are more or less superset of keylime/keylime tests so I won't see it as a priority.

**Comment by ansasaki** [comment]
I'm closing this as I consider that we have good integration tests running for every PR that is created:
- Both this repository and https://github.com/keylime/keylime run the tests from the tests repository (https://github.com/RedHat-SP-Security/keylime-tests) for every created PR using packit.
- `cargo-audit` is executed for every PR, together with `cargo-fmt` and `clippy`
- The python agent implementation was dropped, and there is only the rust agent now
