### ISSUE TITLE
Implement Payload Handling Three Part Key Deviation 

### ISSUE THREAD

**Issue by lukehinds** [keylime/rust-keylime#97]
If an agent passes its attestation, the keylime tenant will provide an encrypted payload. This payload is securely transferred using a key generated by the tenant, and cryptographically split into two, half a key then goes to the verifier and half to the tenant. When an agent passes its attestation, the tenant and the verifier will be release key parts which the agent then combines into a single key that allows them to un-encrypt the payload.

**Comment by lkatalin** [comment]
TODO:

- [ ] Implement tenant container or script to initiate provisioning
- [ ] Agent: receive nonce
- [ ] Agent: Get TPM Quote with PCRs (see quote function [here](https://github.com/parallaxsecond/rust-tss-esapi/blob/main/tss-esapi/src/context/tpm_commands/attestation_commands.rs#L22))
- [ ] Agent: Get TPM Quote without PCRs
- [ ] Agent: Receive V
- [ ] Agent: Receive U
- [ ] Agent: Combine V and U and decrypt payload
